version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
  test:
    build: .
    environment:
      FLASK_ENV: testing
    command: python -m unittest discover -s tests
